### ISSUE TITLE
Packages assume the service name is Neo4j-Server

### ISSUE THREAD

**Issue by glennsarti** [glennsarti/neo4j-community-chocolatey#1]
All of the current packages assume the windows service name is Neo4j-Server.  While this is probably very common, it would be better if the packages read the service name from the neo4j Java wrapper configuration file %NEO4J_HOME%\conf\neo4j-wrapper.conf

**Comment by neutmute** [comment]
My dev box has 4 instances of neo4j running side by side for various apps. A handy update to this choco package would be to use environment variables to configure service name, install location and HTTP/S ports. One would then use `--force` with different env vars to install the side by side environments.

If this sounds OK - I'll do a PR once #8 is resolved

**Comment by glennsarti** [comment]
@neutmute I added the ability to pass in the neo4j-wrapper.conf file as part of the installation;

https://github.com/glennsarti/neo4j-community-chocolatey/tree/master/neo4j-community-2.3.0-M02-beta#what-package-parameters-can-i-use

This will enable you to set the service name etc. during the installation and service creation

**Comment by neutmute** [comment]
I did see that, but if you will indulge me I will try show why env vars are better :)

I recently got into boxstarter

If you don't know boxstarter, this should be enough to explain:
[https://github.com/neutmute/nm-boxstarter/blob/master/base-box.ps1](https://github.com/neutmute/nm-boxstarter/blob/master/base-box.ps1)

Imagine you have a freshly repaved windows (manually installed, vagrant, packer), you need only execute that `START ...` command from the above file, leave it a few hours and you have a fresh machine ready to go.

My goal is to have this be able to run at work this build or home. The `specify-conf-file` technique for this package isn't as portable though - I'd need to publish my conf's in a commonly available location - ie: the public internet. 

The env var way would look something like this - completely self contained and easier for noobs

```
set choco-neo4j-instance-name myAwesomeApp
set choco-neo4j-install-path D:\data\neo4j\
set choco-neo4j-port-http 7480
set choco-neo4j-port-https 7481
choco install neo4j-community
```

if neo4j change conf file formats between versions that change needs only be known by the package ps1 script - not the user.

Of course any PR would keep support for the old way

I already have a powershell script that works similar to this - I wrote it before I got into chocolatey
https://gist.github.com/neutmute/5366279740dc872936c649da634cc08b
so it wouldn't take much to adapt

Have I convinced you yet? :)

**Comment by neutmute** [comment]
Hi @glennsarti Any further thoughts on this? 

See this package I did for [sql server 2016](https://github.com/neutmute/chocolatey-packs/tree/master/sqlserver2016) - you can make the install as simple or complicated as you like without needing to have previously built a configuration.ini

**Comment by glennsarti** [comment]
@neutmute Seems like a good idea then. Happy to take any PRs

**Comment by glennsarti** [comment]
@neutmute I've started work on adding support for it in Neo4j 3.0 packages.  I decided not to use env vars as there is already a mechanism for passing in package installation parameters.  Once I get it working for 3.0 it can be back ported to the latest 2.3 package.

**Comment by neutmute** [comment]
:+1: sounds great - thanks!

**Comment by glennsarti** [comment]
@neutmute 3.0.0-RC1 package is done and is awaiting moderation.  Is there anything else you think would be useful to add?

**Comment by neutmute** [comment]
awesome - I'll test it tonight

**Comment by neutmute** [comment]
I gave it a whirl with this command

`choco install neo4j-community -version 3.0.0-RC1-beta -prerelease -packageParameters "/Install:C:\Apps\Neo\myApp /HTTPSEndpoint:127.0.0.1:7483 /HTTPEndpoint:127.0.0.1:7484 /WindowsServiceName:neo4j-myapp"`

and thought it hadn't worked quite right but it was because the dash in the service name wasn't parsed properly with `-myapp` stripped off. Slight wrinkle but using the variant below works better anyway since there is no control of the 'Neo4j Graph Database` service description prefix:

`C:\Windows\system32>choco install neo4j-community -version 3.0.0-RC1-beta -prerelease -packageParameters "/Install:C:\Apps\Neo\myApp /HTTPSEndpoint:127.0.0.1:7483 /HTTPEndpoint:127.0.0.1:7484 /WindowsServiceName:myapp"`

It would be nice if the zip didn't unzip to the `neozipSubdir` so that the install folder was truly the install folder. After an inplace upgrade to some future `3.0.1` say, the `neo4j-community-3.0.0-RC1` folder name will be misleading as to which version is being run.

The only thing it doesn't have that my gist version has is turning off the auth which is convenient for development. I'll try using auth for development when v3.0 RTM's and if it is annoying I'll PR in a param for that.

:+1: Nice work - thanks!

**Comment by glennsarti** [comment]
New packages have this feature.  Closing the issue.
